Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: mykeypair
      UserData: |
        #!/bin/bash
        echo "memory_limit=2048M" >> /etc/environment  # Memory limit issue
        echo "user=root" >> /etc/environment  # Privileged execution
        echo "ulimit -n 65535" >> /etc/environment  # High file descriptor limit

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mybucket
      AccessControl: Private
      Tags:
        - Key: Environment
          Value: Production

# Vulnerable YAML file with memory limit issue
memory_limit: 2048M  # Hardcoded memory limit

# Privileged execution
user: root  # Hardcoded privileged user

# High file descriptor limit
ulimit: 65535  # Hardcoded high file descriptor limit
